// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppSettings {
  final bool confirmEnabled;
  final String theme;
  final List<String> launchHistory;
  final WindowState? windowState;

  const AppSettings({
    required this.confirmEnabled,
    required this.theme,
    required this.launchHistory,
    this.windowState,
  });

  @override
  int get hashCode =>
      confirmEnabled.hashCode ^
      theme.hashCode ^
      launchHistory.hashCode ^
      windowState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          confirmEnabled == other.confirmEnabled &&
          theme == other.theme &&
          launchHistory == other.launchHistory &&
          windowState == other.windowState;
}

/// A launch item — one entry in the launcher list.
class LaunchItem {
  final String name;
  final String directory;
  final String command;
  final bool confirm;
  final String id;
  final bool selected;
  final String? terminal;
  final String? tag;
  final String? group;

  const LaunchItem({
    required this.name,
    required this.directory,
    required this.command,
    required this.confirm,
    required this.id,
    required this.selected,
    this.terminal,
    this.tag,
    this.group,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      directory.hashCode ^
      command.hashCode ^
      confirm.hashCode ^
      id.hashCode ^
      selected.hashCode ^
      terminal.hashCode ^
      tag.hashCode ^
      group.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchItem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          directory == other.directory &&
          command == other.command &&
          confirm == other.confirm &&
          id == other.id &&
          selected == other.selected &&
          terminal == other.terminal &&
          tag == other.tag &&
          group == other.group;
}

class LaunchPlan {
  final String executable;
  final List<String> args;
  final String workingDir;
  final bool isDangerous;
  final String? terminalOverride;

  const LaunchPlan({
    required this.executable,
    required this.args,
    required this.workingDir,
    required this.isDangerous,
    this.terminalOverride,
  });

  @override
  int get hashCode =>
      executable.hashCode ^
      args.hashCode ^
      workingDir.hashCode ^
      isDangerous.hashCode ^
      terminalOverride.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaunchPlan &&
          runtimeType == other.runtimeType &&
          executable == other.executable &&
          args == other.args &&
          workingDir == other.workingDir &&
          isDangerous == other.isDangerous &&
          terminalOverride == other.terminalOverride;
}

class WindowState {
  final int x;
  final int y;
  final int width;
  final int height;

  const WindowState({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WindowState &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}
