<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Launchpad</RootNamespace>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\launchpad.Core\launchpad.Core.csproj" />
    <ProjectReference Include="..\launchpad.UseCases\launchpad.UseCases.csproj" />
    <ProjectReference Include="..\launchpad.Infrastructure\launchpad.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Fonts\Lucide.ttf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
