//! Contract tests for the pwsh/cmd argv generated by LaunchPlanner (ported
//! from C# TerminalContractTests): the exact escaping (single-quote doubling
//! for pwsh) must work against the real shells in directories with spaces,
//! quotes, semicolons, ampersands and CJK characters. These spawn real
//! processes — no mocks. wt.exe cases are skipped when Windows Terminal is
//! not installed (mirrors the WtFact skip behavior).

use std::io::Read;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::Duration;

use launchpad_tauri_lib::core::models::LaunchItem;
use launchpad_tauri_lib::core::planner::{escape_pwsh_quotes, plan_windows};

const DIR_CASES: &[&str] = &[
    "plain",
    "with space",
    "with'quote",
    "with;semicolon",
    "with&and",
    "中文目录",
];
const MARKER: &str = "CONTRACT_MARKER";

fn scratch() -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "launchpad-int-{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

fn terminal_available(name: &str) -> bool {
    Command::new("where")
        .arg(name)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Spawn a terminal that does not exit on its own; capture output, settle,
/// then kill (mirrors the C# RunTerminal helper).
fn run_terminal(plan: &launchpad_tauri_lib::core::models::LaunchPlan) -> String {
    let mut child = Command::new(&plan.executable)
        .args(&plan.args)
        .current_dir(&plan.working_directory)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn failed");
    std::thread::sleep(Duration::from_millis(2500));
    let _ = child.kill();
    let mut out = String::new();
    if let Some(mut stdout) = child.stdout.take() {
        let _ = stdout.read_to_string(&mut out);
    }
    let _ = child.wait();
    out
}

fn item(dir: &str) -> LaunchItem {
    LaunchItem {
        name: "contract".to_string(),
        directory: dir.to_string(),
        command: format!("Write-Output {MARKER}"),
        confirm: false,
        id: "contract".to_string(),
        selected: false,
        terminal: None,
        tag: None,
        group: None,
    }
}

#[test]
fn pwsh_fallback_runs_in_all_directory_shapes() {
    if !terminal_available("pwsh.exe") {
        eprintln!("pwsh.exe not available; skipping pwsh contract cases");
        return;
    }
    let base = scratch();
    for dir_name in DIR_CASES {
        let target = base.join(dir_name);
        std::fs::create_dir_all(&target).unwrap();
        let plan = plan_windows(&item(&target.display().to_string()), false, true);

        assert_eq!("pwsh.exe", plan.executable);
        // The single-quote doubling must survive the shell (escaped dir).
        let out = run_terminal(&plan);
        assert!(
            out.contains(MARKER),
            "dir {dir_name:?}: marker missing, output: {out:?}"
        );
        let _ = std::fs::remove_dir_all(&target);
    }
}

#[test]
fn pwsh_escape_doubles_quotes_in_directory() {
    assert_eq!(r"D:\a''b", escape_pwsh_quotes(r"D:\a'b"));
}

#[test]
fn cmd_fallback_runs_in_all_directory_shapes() {
    if !terminal_available("cmd.exe") {
        eprintln!("cmd.exe not available; skipping cmd contract cases");
        return;
    }
    let base = scratch();
    for dir_name in DIR_CASES {
        let target = base.join(dir_name);
        std::fs::create_dir_all(&target).unwrap();
        // cmd uses `echo` (Write-Output is PowerShell syntax).
        let mut it = item(&target.display().to_string());
        it.command = format!("echo {MARKER}");
        let plan = plan_windows(&it, false, false);

        assert_eq!("cmd.exe", plan.executable);
        // cmd /k takes the bare command; the directory travels via
        // WorkingDirectory so quoting traps are avoided entirely.
        assert_eq!(vec!["/k".to_string(), it.command.clone()], plan.args);
        let out = run_terminal(&plan);
        assert!(
            out.contains(MARKER),
            "dir {dir_name:?}: marker missing, output: {out:?}"
        );
        let _ = std::fs::remove_dir_all(&target);
    }
}

#[test]
fn wt_path_skips_when_windows_terminal_missing() {
    // Mirrors the C# WtFact skip: if wt.exe is present the plan must use it;
    // if not, the planner must fall back — both are contract-checked here.
    let it = item(r"D:\projects\demo");
    let plan = plan_windows(&it, terminal_available("wt.exe"), true);
    if terminal_available("wt.exe") {
        assert_eq!("wt.exe", plan.executable);
    } else {
        assert_ne!("wt.exe", plan.executable);
    }
}
