// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 492774567;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_launchpad_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String? crateApiSimpleDangerousReasonStr({required String command});

  Future<void> crateApiSimpleInitApp();

  bool crateApiSimpleIsDangerousCmd({required String command});

  bool crateApiSimpleLaunchItem({required LaunchItem item});

  LaunchPlan crateApiSimplePlanLaunch({required LaunchItem item});

  List<LaunchItem> crateApiSimpleReadItems({required String configDir});

  AppSettings crateApiSimpleReadSettings({required String configDir});

  void crateApiSimpleWriteItems({
    required String configDir,
    required List<LaunchItem> items,
  });

  void crateApiSimpleWriteSettings({
    required String configDir,
    required AppSettings settings,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String? crateApiSimpleDangerousReasonStr({required String command}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDangerousReasonStrConstMeta,
        argValues: [command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDangerousReasonStrConstMeta =>
      const TaskConstMeta(
        debugName: "dangerous_reason_str",
        argNames: ["command"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiSimpleIsDangerousCmd({required String command}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(command, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsDangerousCmdConstMeta,
        argValues: [command],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsDangerousCmdConstMeta =>
      const TaskConstMeta(debugName: "is_dangerous_cmd", argNames: ["command"]);

  @override
  bool crateApiSimpleLaunchItem({required LaunchItem item}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_launch_item(item, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleLaunchItemConstMeta,
        argValues: [item],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleLaunchItemConstMeta =>
      const TaskConstMeta(debugName: "launch_item", argNames: ["item"]);

  @override
  LaunchPlan crateApiSimplePlanLaunch({required LaunchItem item}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_launch_item(item, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_launch_plan,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePlanLaunchConstMeta,
        argValues: [item],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePlanLaunchConstMeta =>
      const TaskConstMeta(debugName: "plan_launch", argNames: ["item"]);

  @override
  List<LaunchItem> crateApiSimpleReadItems({required String configDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_launch_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleReadItemsConstMeta,
        argValues: [configDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReadItemsConstMeta =>
      const TaskConstMeta(debugName: "read_items", argNames: ["configDir"]);

  @override
  AppSettings crateApiSimpleReadSettings({required String configDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleReadSettingsConstMeta,
        argValues: [configDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReadSettingsConstMeta =>
      const TaskConstMeta(debugName: "read_settings", argNames: ["configDir"]);

  @override
  void crateApiSimpleWriteItems({
    required String configDir,
    required List<LaunchItem> items,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configDir, serializer);
          sse_encode_list_launch_item(items, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleWriteItemsConstMeta,
        argValues: [configDir, items],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleWriteItemsConstMeta => const TaskConstMeta(
    debugName: "write_items",
    argNames: ["configDir", "items"],
  );

  @override
  void crateApiSimpleWriteSettings({
    required String configDir,
    required AppSettings settings,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(configDir, serializer);
          sse_encode_box_autoadd_app_settings(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleWriteSettingsConstMeta,
        argValues: [configDir, settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleWriteSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "write_settings",
        argNames: ["configDir", "settings"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppSettings dco_decode_app_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AppSettings(
      confirmEnabled: dco_decode_bool(arr[0]),
      theme: dco_decode_String(arr[1]),
      launchHistory: dco_decode_list_String(arr[2]),
      windowState: dco_decode_opt_box_autoadd_window_state(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_app_settings(raw);
  }

  @protected
  LaunchItem dco_decode_box_autoadd_launch_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_launch_item(raw);
  }

  @protected
  WindowState dco_decode_box_autoadd_window_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_window_state(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  LaunchItem dco_decode_launch_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return LaunchItem(
      name: dco_decode_String(arr[0]),
      directory: dco_decode_String(arr[1]),
      command: dco_decode_String(arr[2]),
      confirm: dco_decode_bool(arr[3]),
      id: dco_decode_String(arr[4]),
      selected: dco_decode_bool(arr[5]),
      terminal: dco_decode_opt_String(arr[6]),
      tag: dco_decode_opt_String(arr[7]),
      group: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  LaunchPlan dco_decode_launch_plan(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LaunchPlan(
      executable: dco_decode_String(arr[0]),
      args: dco_decode_list_String(arr[1]),
      workingDir: dco_decode_String(arr[2]),
      isDangerous: dco_decode_bool(arr[3]),
      terminalOverride: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<LaunchItem> dco_decode_list_launch_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_launch_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  WindowState? dco_decode_opt_box_autoadd_window_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_window_state(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WindowState dco_decode_window_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WindowState(
      x: dco_decode_i_32(arr[0]),
      y: dco_decode_i_32(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_confirmEnabled = sse_decode_bool(deserializer);
    var var_theme = sse_decode_String(deserializer);
    var var_launchHistory = sse_decode_list_String(deserializer);
    var var_windowState = sse_decode_opt_box_autoadd_window_state(deserializer);
    return AppSettings(
      confirmEnabled: var_confirmEnabled,
      theme: var_theme,
      launchHistory: var_launchHistory,
      windowState: var_windowState,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_app_settings(deserializer));
  }

  @protected
  LaunchItem sse_decode_box_autoadd_launch_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_launch_item(deserializer));
  }

  @protected
  WindowState sse_decode_box_autoadd_window_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_window_state(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  LaunchItem sse_decode_launch_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_directory = sse_decode_String(deserializer);
    var var_command = sse_decode_String(deserializer);
    var var_confirm = sse_decode_bool(deserializer);
    var var_id = sse_decode_String(deserializer);
    var var_selected = sse_decode_bool(deserializer);
    var var_terminal = sse_decode_opt_String(deserializer);
    var var_tag = sse_decode_opt_String(deserializer);
    var var_group = sse_decode_opt_String(deserializer);
    return LaunchItem(
      name: var_name,
      directory: var_directory,
      command: var_command,
      confirm: var_confirm,
      id: var_id,
      selected: var_selected,
      terminal: var_terminal,
      tag: var_tag,
      group: var_group,
    );
  }

  @protected
  LaunchPlan sse_decode_launch_plan(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_executable = sse_decode_String(deserializer);
    var var_args = sse_decode_list_String(deserializer);
    var var_workingDir = sse_decode_String(deserializer);
    var var_isDangerous = sse_decode_bool(deserializer);
    var var_terminalOverride = sse_decode_opt_String(deserializer);
    return LaunchPlan(
      executable: var_executable,
      args: var_args,
      workingDir: var_workingDir,
      isDangerous: var_isDangerous,
      terminalOverride: var_terminalOverride,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LaunchItem> sse_decode_list_launch_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LaunchItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_launch_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WindowState? sse_decode_opt_box_autoadd_window_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_window_state(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WindowState sse_decode_window_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_i_32(deserializer);
    var var_y = sse_decode_i_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return WindowState(
      x: var_x,
      y: var_y,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.confirmEnabled, serializer);
    sse_encode_String(self.theme, serializer);
    sse_encode_list_String(self.launchHistory, serializer);
    sse_encode_opt_box_autoadd_window_state(self.windowState, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_app_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_launch_item(
    LaunchItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_launch_item(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_window_state(
    WindowState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_window_state(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_launch_item(LaunchItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.directory, serializer);
    sse_encode_String(self.command, serializer);
    sse_encode_bool(self.confirm, serializer);
    sse_encode_String(self.id, serializer);
    sse_encode_bool(self.selected, serializer);
    sse_encode_opt_String(self.terminal, serializer);
    sse_encode_opt_String(self.tag, serializer);
    sse_encode_opt_String(self.group, serializer);
  }

  @protected
  void sse_encode_launch_plan(LaunchPlan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.executable, serializer);
    sse_encode_list_String(self.args, serializer);
    sse_encode_String(self.workingDir, serializer);
    sse_encode_bool(self.isDangerous, serializer);
    sse_encode_opt_String(self.terminalOverride, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_launch_item(
    List<LaunchItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_launch_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_window_state(
    WindowState? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_window_state(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_window_state(WindowState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.x, serializer);
    sse_encode_i_32(self.y, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }
}
