// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<LaunchItem> readItems({required String configDir}) =>
    RustLib.instance.api.crateApiSimpleReadItems(configDir: configDir);

void writeItems({required String configDir, required List<LaunchItem> items}) =>
    RustLib.instance.api.crateApiSimpleWriteItems(
      configDir: configDir,
      items: items,
    );

AppSettings readSettings({required String configDir}) =>
    RustLib.instance.api.crateApiSimpleReadSettings(configDir: configDir);

void writeSettings({
  required String configDir,
  required AppSettings settings,
}) => RustLib.instance.api.crateApiSimpleWriteSettings(
  configDir: configDir,
  settings: settings,
);

bool launchItem({required LaunchItem item}) =>
    RustLib.instance.api.crateApiSimpleLaunchItem(item: item);

bool isDangerousCmd({required String command}) =>
    RustLib.instance.api.crateApiSimpleIsDangerousCmd(command: command);

String? dangerousReasonStr({required String command}) =>
    RustLib.instance.api.crateApiSimpleDangerousReasonStr(command: command);

LaunchPlan planLaunch({required LaunchItem item}) =>
    RustLib.instance.api.crateApiSimplePlanLaunch(item: item);
