using System.Diagnostics;
using Launchpad.Core.Domain;
using Launchpad.Core.Models;
using Launchpad.Infrastructure;
using Xunit;

namespace Launchpad.IntegrationTests;

/// <summary>
/// Contract tests for the pwsh/cmd/wt argv generated by <see cref="LaunchPlanner"/>:
/// the exact escaping (single-quote doubling for pwsh, double-quote doubling for cmd)
/// must work against the real shells. These spawn real processes — no mocks.
/// </summary>
public sealed class TerminalContractTests : IDisposable
{
    private readonly string _baseDir =
        Path.Combine(Path.GetTempPath(), "launchpad-int-" + Guid.NewGuid().ToString("N"));

    public TerminalContractTests()
    {
        Directory.CreateDirectory(_baseDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_baseDir))
        {
            // wt 测试启动的终端可能仍持有目录；临时目录残留可接受
            try
            {
                Directory.Delete(_baseDir, recursive: true);
            }
            catch (IOException)
            {
            }
        }
    }

    public static IEnumerable<object[]> DirCases()
    {
        yield return new object[] { "plain" };
        yield return new object[] { "with space" };
        yield return new object[] { "with'quote" };
        yield return new object[] { "with;semicolon" };
        yield return new object[] { "with&and" };
        yield return new object[] { "中文目录" };
    }

    private string MakeTarget(string dirName)
    {
        var target = Path.Combine(_baseDir, dirName);
        Directory.CreateDirectory(target);
        return target;
    }

    private static LaunchItem Item(string dir) => new()
    {
        Name = "contract",
        Directory = dir,
        Command = "Write-Output CONTRACT_MARKER",
        Confirm = false,
        Id = "contract",
        Selected = false,
    };

    /// <summary>Run a terminal that does not exit on its own; kill after the settle window.</summary>
    private static (string Out, string Err) RunTerminal(ProcessStartInfo psi, int settleMs = 2000)
    {
        using var process = Process.Start(psi);
        Assert.NotNull(process);
        var outTask = process.StandardOutput.ReadToEndAsync();
        var errTask = process.StandardError.ReadToEndAsync();
        Thread.Sleep(settleMs);
        try
        {
            process.Kill(entireProcessTree: true);
        }
        catch (InvalidOperationException)
        {
            // process already exited
        }

        process.WaitForExit();
        return (outTask.Result, errTask.Result);
    }

    [Theory]
    [MemberData(nameof(DirCases))]
    public void Pwsh_CdCommand_ExecutesWithEscapedDirectory(string dirName)
    {
        var target = MakeTarget(dirName);
        var psi = new ProcessStartInfo("pwsh.exe")
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        psi.ArgumentList.Add("-NoExit");
        psi.ArgumentList.Add("-Command");
        psi.ArgumentList.Add($"cd '{LaunchPlanner.EscapePwshQuotes(target)}'; Write-Output CONTRACT_MARKER; Write-Output $PWD");

        var (outText, errText) = RunTerminal(psi);

        Assert.Contains("CONTRACT_MARKER", outText);
        // Windows 路径大小写不敏感；pwsh 会把 TEMP 规范化为 Temp 显示
        Assert.Contains(target, outText, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Cannot find path", errText);
    }

    [Theory]
    [MemberData(nameof(DirCases))]
    public void Cmd_PlannerArgv_ExecutesCommandInWorkingDirectory(string dirName)
    {
        var target = MakeTarget(dirName);
        // cd（无参数）打印当前目录，不经 %CD% 变量展开（含 & 的目录名会破坏展开）
        var item = Item(target) with { Command = "echo CONTRACT_MARKER && cd" };
        var plan = LaunchPlanner.PlanWindows(item, wtAvailable: false, pwshAvailable: false);
        Assert.Equal("cmd.exe", plan.Executable);

        var psi = new ProcessStartInfo(plan.Executable)
        {
            WorkingDirectory = plan.WorkingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var arg in plan.Args)
        {
            psi.ArgumentList.Add(arg);
        }

        var (outText, errText) = RunTerminal(psi);

        Assert.Contains("CONTRACT_MARKER", outText);
        Assert.Contains(target, outText, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("not recognized", errText);
    }

    [Fact]
    public void Pwsh_PlannerArgv_ExecutesCommandInRequestedDirectory()
    {
        // The full argv LaunchPlanner emits for the pwsh fallback must cd into the
        // (possibly quote-containing) directory and execute the user command there.
        var target = MakeTarget("planner-argv'with'quotes");
        var item = Item(target) with { Command = "Write-Output $PWD" };
        var plan = LaunchPlanner.PlanWindows(item, wtAvailable: false, pwshAvailable: true);
        Assert.Equal("pwsh.exe", plan.Executable);

        var psi = new ProcessStartInfo(plan.Executable)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        foreach (var arg in plan.Args)
        {
            psi.ArgumentList.Add(arg);
        }

        var (outText, errText) = RunTerminal(psi);

        Assert.Contains(target, outText, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Cannot find path", errText);
    }

    [WtFact]
    public void Wt_AcceptsPlannerArgv_WhenAvailable()
    {
        var target = MakeTarget("wt-contract");
        var plan = LaunchPlanner.PlanWindows(Item(target), wtAvailable: true, pwshAvailable: true);
        Assert.Equal("wt.exe", plan.Executable);

        // wt.exe is a GUI app: no stdout to capture. The contract here is that the
        // argv is accepted and a terminal window opens (command execution is a
        // manual verification item recorded in the spec).
        var psi = new ProcessStartInfo(plan.Executable) { UseShellExecute = false };
        foreach (var arg in plan.Args)
        {
            psi.ArgumentList.Add(arg);
        }

        using var process = Process.Start(psi);
        Assert.NotNull(process);
        Thread.Sleep(2000);
        if (!process.HasExited)
        {
            process.Kill(entireProcessTree: true);
        }
    }
}
